name = "BilevelTrajOpt"
uuid = "9688c538-179f-11e9-3174-495cea6b7f67"
authors = ["blandry <blandry@stanford.edu>"]
version = "0.1.0"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GeometryTypes = "4d00f742-c7ba-57c2-abde-4428a4b178cb"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
MechanismGeometries = "931e9471-e8fb-5385-a477-07ad12718aca"
RigidBodyDynamics = "366cf18f-59d5-5db9-a4de-86a9f6786172"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
