name = "Bilevel"
uuid = "9688c538-179f-11e9-3174-495cea6b7f67"
authors = ["blandry <blandry@stanford.edu>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CodecBzip2 = "523fee87-0ab8-5b00-afb7-3ecf72e48cfd"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DiffResults = "163ba53b-c6d8-5494-b064-1a9d43ac40c5"
FastIOBuffers = "6ccb8d0d-f5f8-5ae0-a392-f5aa62729a81"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GeometryTypes = "4d00f742-c7ba-57c2-abde-4428a4b178cb"
InteractBase = "d3863d7c-f0c8-5437-a7b4-3ae773c01009"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MechanismGeometries = "931e9471-e8fb-5385-a477-07ad12718aca"
MeshCat = "283c5d60-a78f-5afe-a0af-af636b173e11"
MeshCatMechanisms = "6ad125db-dd91-5488-b820-c1df6aab299d"
Mux = "a975b10e-0019-58db-a62f-e48ff68538c9"
OSQP = "ab2f91bb-94b4-55e3-9ba0-7f65df51de79"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProfileView = "c46f51b8-102a-5cf2-8d2c-8597cb0e0da7"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
RigidBodyDynamics = "366cf18f-59d5-5db9-a4de-86a9f6786172"
RobotOS = "22415677-39a4-5241-a37a-00beabbbdae8"
RobotOSData = "f566df43-e85a-5b37-8f32-e64a053ee570"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Tokenize = "0796e94c-ce3b-5d07-9a54-7f471281c624"
TranscodingStreams = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"
WebIO = "0f1e0344-ec1d-5b48-a673-e5cf874b6c29"
